---
deployment:
  tasks:
    - export DEPLOYPATH=/home/vizajeni/public_html
    - /bin/cp -r . $DEPLOYPATH
    - cd $DEPLOYPATH && /usr/local/bin/composer install --no-dev --optimize-autoloader --no-interaction
