---
deployment:
  tasks:
    - export DEPLOYPATH=/home/vizajeni/public_html/
    - /usr/local/bin/composer install --no-dev --optimize-autoloader
      --no-interaction
    - /bin/rsync -a --exclude=".git/" --exclude=".env"
      --exclude="application/config/database.php" --exclude="application/logs/"
      --exclude="public/uploads/" ./ $DEPLOYPATH
